---

version: '3.7'

services:

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
##    command: export TESSDATA_PREFIX=/Users/faithsmetanova/Git/Learning/manga-ocr-api/tessdata
##    volumes:
##      - './config.yml:/app/config.yml'
#    ports:
#      - 8081:8081
##      - 8000:8000

  app:
    # image: manga-app-server4:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './manga:/app/manga'
    ports:
      - 8081:8081

  j-token:
    image: himkt/konoha:latest
    ports:
      - 8000:8000
